# User.create(name: "Noly", last_name: "Franco", username:"nolyF", password: "1234", email: "noly@gmail.com", birthday: "08/17/2001", image:"https://avatars2.githubusercontent.com/u/19509797?s=400&v=4")
# User.create(name: "Anna", last_name: "Brakowska", username:"anna", password: "123456", email: "ana@gmail.com", birthday: "01/01/1990", image:"https://avatars1.githubusercontent.com/u/16248495?s=460&v=4")

# Article.create(title:'The Reign of Recycling', image: 'https://static01.nyt.com/images/2015/10/04/opinion/sunday/04tierneyWEB/04tierneyWEB-superJumbo.jpg?quality=90&auto=webp', text_content:'IF you live in the United States, you probably do some form of recycling. It’s likely that you separate paper from plastic and glass and metal. You rinse the bottles and cans, and you might put food scraps in a container destined for a composting facility. As you sort everything into the right bins, you probably assume that recycling is helping your community and protecting the environment. But is it? Are you in fact wasting your time?
#     In 1996, I wrote a long article for The New York Times Magazine arguing that the recycling process as we carried it out was wasteful. I presented plenty of evidence that recycling was costly and ineffectual, but its defenders said that it was unfair to rush to judgment. Noting that the modern recycling movement had really just begun just a few years earlier, they predicted it would flourish as the industry matured and the public learned how to recycle properly.
#     So, what’s happened since then? While it’s true that the recycling message has reached more people than ever, when it comes to the bottom line, both economically and environmentally, not much has changed at all.
#     Despite decades of exhortations and mandates, it’s still typically more expensive for municipalities to recycle household waste than to send it to a landfill. Prices for recyclable materials have plummeted because of lower oil prices and reduced demand for them overseas. The slump has forced some recycling companies to shut plants and cancel plans for new technologies. The mood is so gloomy that one industry veteran tried to cheer up her colleagues this summer with an article in a trade journal titled, “Recycling Is Not Dead!”
#     ' , user_id: 1, article_date: 20180814)

